services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: nephrosys
      POSTGRES_USER: nephrosys
      POSTGRES_PASSWORD: nephrosys_dev
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
