# -*- coding: utf-8 -*-
{
    'name': 'ACS HMS Nephrology Billing',
    'version': '1.0.0',
    'category': 'Healthcare',
    'summary': 'Facturation des séances de dialyse — tarification, assurances, solde patient',
    'depends': ['acs_hms_nephrology', 'account', 'mail'],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'data/ir_cron.xml',
        'data/mail_template.xml',
        'views/pricing_rule_views.xml',
        'views/insurer_views.xml',
        'report/report_monthly.xml',
        'report/report_patient.xml',
        'views/config_settings_views.xml',
        'views/patient_views.xml',
        'views/procedure_views.xml',
        'views/account_move_views.xml',
        'views/bulk_invoice_views.xml',
        'views/monthly_report_views.xml',
        'views/excel_export_views.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
